server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysystem?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
mybatis-plus:
  mapper-locations: classpath*:com/jxd/order/dao/mapping/*.xml
  type-aliases-package: com.jxd.order.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
